# NumPy Arrays

In [1]:
num=[1,2,3]

In [2]:
import numpy as np

In [5]:
arr=np.array(num) # creating 1d array

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
arr_2=np.array(mat) # creating 2-d array

In [10]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# creating an nump array within a range
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#creating an 1-d array of zeros
np.zeros(3)

array([0., 0., 0.])

In [13]:
#creating an 2-d array of zeros
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#creating an 1-d array of ones
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
#creating an 2-d array of ones
np.ones((7,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
#builtin numpy method to create evenly spaced no. of arrays within a particular range
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [17]:
#creating a identity matrix by numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#creating a matrice of random distributed arrays from a uniform distribution
np.random.rand(4,5)

array([[0.84518791, 0.00585439, 0.29416477, 0.10286973, 0.85539967],
       [0.38829699, 0.05100567, 0.70313179, 0.43986106, 0.77293397],
       [0.98629362, 0.81503871, 0.92294719, 0.6513169 , 0.59038634],
       [0.76043074, 0.15483749, 0.57789352, 0.15809174, 0.78437745]])

In [21]:
#creating a matrice of random distributed arrays from a normal distribution
np.random.randn(5,6)

array([[-0.8764348 , -0.26020823,  0.14836144,  1.42059013, -2.09506432,
        -0.0416928 ],
       [ 1.4191132 ,  0.88860285,  0.24372251, -1.12837266, -0.80032518,
        -0.10973745],
       [ 0.29133935, -0.90282291,  0.26800491, -0.7100245 ,  1.23990582,
        -1.34410933],
       [-0.43054494, -0.31468789,  0.02811832, -0.07525389, -0.00866033,
        -0.17405529],
       [-1.16317248,  0.55210556, -1.22080257, -1.47501726,  1.75813083,
        -0.83513196]])

In [23]:
#creating a matrice of random distributed arrays of integers
np.random.randint(1,5,10)

array([4, 4, 4, 4, 3, 2, 4, 1, 1, 1])

In [25]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
#reshaping of 1-d array
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
num=np.random.randint(0,50,10)

In [29]:
num

array([34, 13, 44, 33, 46, 31, 16, 19, 27,  8])

In [30]:
#finding max value element
num.max()

46

In [31]:
#find minumum value element
num.min()

8

In [32]:
#finding index value of max value element
num.argmax()

4

In [33]:
#finding index value of minimum value element
num.argmin()

9