# numpy array indexing

In [1]:
import numpy as np

In [2]:
arr= np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
# selecting every elment till 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
# broadcasting in array
arr[:6]=100

In [7]:
arr # sets first 6 elments equal to 100

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [8]:
arr=np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# slice in array is view of actual array and will change the value in original array if chnage the value in slice of array
slic=arr[:6]

In [11]:
slic

array([0, 1, 2, 3, 4, 5])

In [12]:
slic[:]=100

In [13]:
slic

array([100, 100, 100, 100, 100, 100])

In [14]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [15]:
# if want to create a copy of array, we can use inbuilt copy function
copy=arr.copy()

In [16]:
copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [18]:
#creating a 2-d array
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# grabing elements from 2-d array or matrice
arr_2d[0][0]

1

In [21]:
#getting first row
arr_2d[0]

array([1, 2, 3])

In [26]:
# getting the sub matrice of a matrice
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [27]:
#conditional operators in array
arr=np.arange(0,11)
boo=arr>5

In [28]:
boo

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [29]:
arr[boo]

array([ 6,  7,  8,  9, 10])

# numpy operations

In [30]:
arr=np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# adding arrays
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
#subtarcting arrays
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#multiplications of arrays
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [35]:
# adding scalar in array
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [36]:
#square root of array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [38]:
np.max(arr)

10

In [39]:
np.log(arr)

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])